### ISSUE TITLE
Download process

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#163]
When a product is available in a new language, the admin and product manager can upload two PDF files for each language (PDF Production (for printing press) and PDF Personal (for sending digital or printing at home) to the system that users can download after they sign-up to the platform (screenshot0.png)

Download: Step 1
Members can now click on the “Download” button (see screenshot1.png) to download files. They should first sign-in to download, and will then be directed to a new page (Download Process 1.png) where they have the following options:

--> 1. Select what type of file they want (Print PDF or Digital PDF).

Download: Step 2
The second download process page (Download Process 2.png) should explain to the member that the project depends on supporters and ask them to;

--> 1. Donate via Patreon. We could say something like, "We need 200 people to donate $50 or more per month".
--> 2. Share Adventist Commons platform via Social Media
--> 3. Invite others to Adventist Commons via email.

Download: Step 3
When they click to the next page (Download Process 3.png), the download button for the selected PDF file the members wants should only be active if he agrees to the CC BY-ND 4.0 terms which are described. We also need to add here that they are not allowed to translate this product except through our platform, and a few short other information they need to note such that Printers needs add to the product for offset printing the location etc.

After the users downloads the product we need to make an entry into the database that keeps track about which users has downloaded which product. Even if a user deletes his account we should still be able to keep track of the amount of downloads. Users should also see their download history.

**Comment by m-dotcom** [comment]
Signed in as translator and tried to download the "original" but nothing happens and it also preventing me from accessing my personal account. 

![Screen Shot 2020-04-07 at 12 09 35 PM](https://user-images.githubusercontent.com/51795720/78651212-b1342b80-78c8-11ea-8a72-2c98ef749eee.png)

**Comment by m-dotcom** [comment]
Let me know if there is something I need to do....

**Comment by m-dotcom** [comment]
I could now download the original English but it didn't tricker any of the download sequence. 

Also, could it be that the download button for each project is only visible to users when the status of the project is "ready for download"?

**Comment by m-dotcom** [comment]
I cannot login on develop. somehow as translator. Not sure why.

**Comment by vibby** [comment]
Actually, you are logged in. But the dashboard page is empty. I fixed that.

**Comment by m-dotcom** [comment]
Same problem still. Stuck on the below screen. If I am logged in after all I can download the English file without any download sequence. Signed in as translator. 

![Screen Shot 2020-04-10 at 11 50 04 AM](https://user-images.githubusercontent.com/51795720/78978043-c8ba2100-7b21-11ea-9f2b-17383e83f8a3.png)

**Comment by vibby** [comment]
Hum I have no idea what is happening with you. I can log-in successfully with either my account, the translator, the admin …

**Comment by m-dotcom** [comment]
Finally... connected through VPN to Germany and it works. 

1. Can you make the twitter sharing link open in a new window?
2. I can still download the original English files without the download process but for the other projects it is working perfectly. Thanks Vincent, great job!!

**Comment by vibby** [comment]
Ok I understand it. So we finally have two technical storage of original files, in product edit and through attachments. I now remove the the ability to set them in prodct edit, but only keep the uploaders you asked me to add.

**Comment by m-dotcom** [comment]
Thanks Vincent. Maybe we misunderstood each other regarding that feature. Sorry about that and thanks for changing it in the "edit" in product. It makes sense now to me. 

When I am logged in as admin I can now complete the download and it takes me through the download process. Other members (translator, proofreader, and reviewer) should also be able to do that.

**Comment by vibby** [comment]
It should be ok Michael. I did the test on my computer. I also looked on develop and I do not see any product with an upload original file. Where did you test that ? 
Please note only product managers can download original idml file, and download process do not apply then. Is that ok for you ?

**Comment by m-dotcom** [comment]
I just uploaded a test PDF to "The Silent Killer" tract to test. 

Yes, only product manager and admins needs to have access to IDML. 

If I upload PDFs to a project, they only become available for download if project status is "ready to download" correct?

**Comment by vibby** [comment]
At the moment, if a pdf is uploaded to a project anyone can download it. You told me product managers are aware of it and won’t upload if it’s not ready yet.

**Comment by m-dotcom** [comment]
Yes you are right. But right now if I upload PDFs to a project and login as translators, somehow I cannot see a download button for the project and was wondering why.

The feature to make only downloadable at right status is good but not needed right now. After beta. 

IDMLs can only be downloaded by product manager and admins. 

Thanks Vincent.

**Comment by vibby** [comment]
ok done

**Comment by m-dotcom** [comment]
IDML download for admin works. 

Where can I find the PDF download for a project when I am logged in as normal translator (member)?

**Comment by vibby** [comment]
my bad

**Comment by m-dotcom** [comment]
Perfect!
